# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Halfmind
version: "1.2.0"
slug: halfmind
description: Add-on for Halfmind devices and services
url: "https://github.com/ChangeClock/Halfmind-Addon/addons-example/tree/main/example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/home-assistant/{arch}-halfmind"
